### ISSUE TITLE
Change install instructions back to using anaconda?

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/tutorial#1]
numpy doesn't exist on conda-forge for windows. We currently ask people to install it from conda-forge, which means things are broken for people with windows.

Either (a) use the anaconda numpy, or (b) don't install numpy, scipy, etc. with the basic installation instructions, and then install those with the extra widget examples if needed (and maybe install from anaconda?)

**Comment by jasongrout** [comment]
CC @SylvainCorlay

**Comment by mwcraig** [comment]
Closing, since we are back to using defaults, I think...
