### ISSUE TITLE
problem installing jupyter widgets

### ISSUE THREAD

**Issue by matthewspink** [jupyter-widgets/tutorial#110]
I have run through most the setup which seems to have worked well however when I get to the below step I get the following error

PS C:\Users\wfm82120\Desktop\scipy\widgets\tutorial-master> jupyter labextension install @jupyter-widgets/jupyterlab-manager @jupyter-widgets/jupyterlab-sidecar bqplot jupyte
r-threejs jupyter-leaflet@0.12.6 ipysheet ipytree ipycanvas jupyter-matplotlib jupyter-vuetify ipyvolume
Unrecognized token in source text.
At line:1 char:30
+ jupyter labextension install  <<<< @jupyter-widgets/jupyterlab-manager @jupyter-widgets/jupyterlab-sidecar bqplot jupyter-threejs jupyter-leaflet@0.12.6 ipysheet ipytree i
pycanvas jupyter-matplotlib jupyter-vuetify ipyvolume
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnrecognizedToken

any suggestions would be greatly appreciated

**Comment by martinRenou** [comment]
Thanks for opening an issue, it seems to be a PowerShell parsing issue, what if you run:
```
jupyter labextension install "@jupyter-widgets/jupyterlab-manager" "@jupyter-widgets/jupyterlab-sidecar" bqplot jupyter-threejs "jupyter-leaflet@0.12.6" ipysheet ipytree ipycanvas jupyter-matplotlib jupyter-vuetify ipyvolume
```

**Comment by matthewspink** [comment]
That worked, thanks very much for your help
