### ISSUE TITLE
Add `ReviewNB` to this github repo

### ISSUE THREAD

**Issue by ianhi** [jupyter-widgets/tutorial#180]
Could be nice to add https://www.reviewnb.com/

Thoughts?

**Comment by mwcraig** [comment]
Yes!

**Comment by ianhi** [comment]
I got this far and clicked `request`. Not sure who that goes to

![image](https://user-images.githubusercontent.com/10111092/174160619-3fdd84b6-1ae9-4b76-b2c8-8932742c4d20.png)

**Comment by mwcraig** [comment]
I was able to approve the request so it should work now.
