### ISSUE TITLE
ipygany is wonky

### ISSUE THREAD

**Issue by marimeireles** [jupyter-widgets/tutorial#186]
I'm not sure exactly why because I have no error messages, but the rendering of objs that use the `TetraMesh` look pretty bad:

<img width="338" alt="Screenshot 2022-07-03 at 18 42 31" src="https://user-images.githubusercontent.com/17600982/177058168-c4206871-846f-4286-b7d5-b69ec588bcad.png">

Do you have any idea for what's a good substitute?
Was thinking about going through 07-05 instead of using `ipygany` if you don't have any strong thoughts on it.

I know we always try to have a 3d rendering widget, correct? But not sure what to show.

I appreciate inputs!

**Comment by mwcraig** [comment]
Hmm, fine question. I remember this one being finicky before (sensitive to the min/max thresholds) but I don't remember them looking quite this bad.

Maybe drop those two examples?

**Comment by marimeireles** [comment]
You think it might be that?
That's weird cause it was working last year! 😅
I'll try to play with the thresholds, let's see.
